### ISSUE TITLE
Can't get it to animate or change states

### ISSUE THREAD

**Issue by seanhess** [amichnia/ASIACheckmarkView#1]
Hi, I'm very excited about the component you've made here, but I can't seem to get to change states. I've placed it in a storyboard as a button, set the custom class, and linked it to an outlet. I haven't changed any properties yet. 

Then this function is set as an IBAction for when it is tapped:

```
    @IBAction func tapCheck(sender: AnyObject) {
        print("CHECK TAP", checkmark.boolValue)
        let newValue = !checkmark.boolValue // boolValue describes current checkmark state
        checkmark.animateTo(newValue) // animate to state you wan
    }
```

It gets called, and checkmark.boolValue is alternating between true and false, but it isn't changing states. 

Note that if I change the properties in IB they are different when the app loads, but I still can't get it to change states. 

Thanks!

**Comment by seanhess** [comment]
Wait, nvm, it just started working. No idea what I changed. Sorry.

**Comment by amichnia-pgs** [comment]
Hey - no problem. If you have any comments, or requests - fell free to let me know :)
